### ISSUE TITLE
Change of alias 'signature' from 'synopsis' to 'pluginName'

### ISSUE THREAD

**Issue by simonsigre** [enosysau/TA-tenable-add-on-for-splunk#2]
Previous version of Splunk/Tenable integration mapped the `CIM` field 'signature` to the `pluginName` field however the Tenable maintained TA maps this instead to `synopsis` .. which does not match the `CIM` description of the intended use for this (https://docs.splunk.com/Documentation/CIM/4.14.0/User/Vulnerabilities).

My suggestion is that the alias be default 

`signature` = `pluginName`

Currently ;

sourcetype | signature | pluginName | synopsis
-- | -- | -- | --
tenable:sc:vuln | A web browser installed on the remote host is affected by multiple vulnerabilities. | Google Chrome < 72.0.3626.81 Multiple Vulnerabilities | A web browser installed on the remote host is affected by multiple vulnerabilities.
tenable:sc:vuln | A web browser installed on the remote host is affected by multiple vulnerabilities. | Google Chrome < 73.0.3683.75 Multiple Vulnerabilities | A web browser installed on the remote host is affected by multiple vulnerabilities.

Proposed;

sourcetype | signature | pluginName | synopsis
-- | -- | -- | --
tenable:sc:vuln | Google Chrome < 72.0.3626.81 Multiple Vulnerabilities | Google Chrome < 72.0.3626.81 Multiple Vulnerabilities | A web browser installed on the remote host is affected by multiple vulnerabilities.
tenable:sc:vuln | Google Chrome < 73.0.3683.75 Multiple Vulnerabilities | Google Chrome < 73.0.3683.75 Multiple Vulnerabilities | A web browser installed on the remote host is affected by multiple vulnerabilities.

This appears to be the case for `Tenable.io` also;
e.g. 
```
tenable:io:vuln : FIELDALIAS-signature	plugin.synopsis AS signature
```

**Comment by linsmeyerh** [comment]
Adjustments made for Tenable.io signature as an alias from `plugin.name`.

Fix applied:
```
[tenable:io:vuln]
FIELDALIAS-signature = plugin.name AS signature
```

**Comment by linsmeyerh** [comment]
The fix has been pushed to both stanzas (sourcetypes) `tenable:sc:vuln` and `tenable:io:vuln`.
