### ISSUE TITLE
pluginName values returning BLANK or "

### ISSUE THREAD

**Issue by simonsigre** [enosysau/TA-tenable-add-on-for-splunk#3]
Certain `pluginName` values are either BLANK or contain `"`  under a yet to be determined condition..however I suspect this is majority `"family.name"=SCADA`

sourcetype | type | signature | pluginName | synopsis
-- | -- | -- | -- | --
tenable:sc:vuln |   |   | Generic Protocol Detection |  
tenable:sc:vuln |   |   | "FL-net Reception Protocol Port Server Detection" |  
tenable:sc:vuln |   | The remote host operating system can be detected. | Windows 10 Operating System Detection | The remote host operating system can be detected.
tenable:sc:vuln |   | A Common Platform Enumeration (CPE) has been detected on the remote host. | Common Platform Enumeration (CPE) Detection | A Common Platform Enumeration (CPE) has been detected on the remote host.
tenable:sc:vuln |   | The remote host is running the Firefox web browser. | Mozilla Firefox Version Detection | The remote host is running the Firefox web browser.
tenable:sc:vuln |   | The HTTP 'User-Agent' request header has been detected. | HTTP 'User-Agent' Request Header Detection | The HTTP 'User-Agent' request header has been detected.
tenable:sc:vuln |   | The remote host supports the use of 64-bit block ciphers. | SSL 64-bit Block Size Cipher Suites Supported (SWEET32) | The remote host supports the use of 64-bit block ciphers.
tenable:sc:vuln |   | The remote host is an SSL/TLS client. | SSL Client Detection | The remote host is an SSL/TLS client.
tenable:sc:vuln |   |   | ICMP Activity |  
tenable:sc:vuln |   |   | Generic Protocol Detection

**Comment by simonsigre** [comment]
Confirmed the only values returned are for `"family.name"=SCADA`

![Screenshot from 2020-01-08 11-48-55](https://user-images.githubusercontent.com/14932913/71941213-0cdd1300-320d-11ea-8fcd-402aa615d678.png)

**Comment by linsmeyerh** [comment]
This issue will remain open in case the same issue is noted on Tenable.io logs.

**Comment by linsmeyerh** [comment]
This issue has been resolved as we moved the field `signature` from been an alias from synopsis to an `EVAL` field (creating the field signature) filtering the values of the `pluginName` replacing the BLANK or quote (") marks. The fix has been applied to the code as part of the issue #2
