### ISSUE TITLE
Support for 'Vulnerabilities' Datamodel: `dest` field

### ISSUE THREAD

**Issue by Edmund-Tran** [enosysau/TA-tenable-add-on-for-splunk#6]
The `tenable:io:vuln` data we're seeing requires some extra field aliasing/extraction for the `dest` field such that it'll be compliant with the `Vulnerabilities` datamodel. Historically, we've been expecting `ip` values in the `dest` fields so can pivot off the `ipv4` or `ipv6` (if `ipv4` is null) fields?

**Comment by linsmeyerh** [comment]
There is a bug on the Add-on version 3.0 and 3.1 props.conf stanza [tenable:io:vuln] which uses the wrong command to create the field `dest`; wrongly using `EVAL` command instead of `FIELDALIAS`.

Current configuration:
```
EVAL-dest = ipv4 AS dest
```
Fix applied:
```
FIELDALIAS-dest = ipv4 AS dest
```

The issue has been corrected and fixes pushed to the repo.
